### ISSUE TITLE
Django 1.7.1 ImportError: cannot import name simplejson

### ISSUE THREAD

**Issue by strindhaug** [ella/django-appdata#7]
After installing aldryn-blog which requires django-appdata, any ´python manage.py´ command fails with the following stacktrace:

    Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "<my-virtualenv-site-packages-dir>/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "<my-virtualenv-site-packages-dir>/django/core/management/__init__.py", line 354, in execute
        django.setup()
      File "<my-virtualenv-site-packages-dir>/django/__init__.py", line 21, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "<my-virtualenv-site-packages-dir>/django/apps/registry.py", line 108, in populate
        app_config.import_models(all_models)
      File "<my-virtualenv-site-packages-dir>/django/apps/config.py", line 202, in import_models
        self.models_module = import_module(models_module_name)
      File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "<my-virtualenv-site-packages-dir>/aldryn_blog/models.py", line 13, in <module>
        from app_data import AppDataField
      File "<my-virtualenv-site-packages-dir>/app_data/__init__.py", line 1, in <module>
        from .fields import AppDataField, ListModelMultipleChoiceField
      File "<my-virtualenv-site-packages-dir>/app_data/fields.py", line 2, in <module>
        from django.utils import simplejson as json
    ImportError: cannot import name simplejson

Apparently this has been deprecated since django 1.5:
https://docs.djangoproject.com/en/1.5/releases/1.5/#django-utils-simplejson
and its removed in 1.7:
https://docs.djangoproject.com/en/dev/releases/1.7/#features-removed-in-1-7

So, how do I fix this? Apparently it's not even needed since json is now standard.

**Comment by mkoistinen** [comment]
Is there a date for which a PyPI release is planned?

**Comment by mkoistinen** [comment]
Or, perhaps we can get a 'tag' for the current build? Its a bit more complicated to add as a dependency to other Django 1.7 projects at this moment.

**Comment by HonzaKral** [comment]
1.7 compatibility was just introduced in 635be13. I will be super happy for any testing. If it works I will do a release on PyPI.

Thanks

**Comment by tomassommar** [comment]
Any updates on when a PyPI release is planned?

**Comment by kvbik** [comment]
new version released [1], thx @HonzaKral for fixes, thank you all for using this lib :)

[1] https://pypi.python.org/pypi/django-appdata/0.1.4
